Transform: AWS::Serverless-2016-10-31 # Need for all SAM templates, Source: https://docs.aws.amazon.com/serverless-application-model/latest/developerguide/sam-specification-template-anatomy.html

Resources:
  ApiGatewayApi:
    Type: AWS::Serverless::Api
    Properties:
      StageName: prod
  ApiFunction: # Adds a GET method at the root resource via an Api event
    Type: AWS::Serverless::Function
    Properties:
      Events:
        TestGet: # This defines the url for this endpoint
          Type: Api
          Properties:
            Path: /dummy
            Method: get
            RestApiId:
              Ref: ApiGatewayApi
      CodeUri: endpoints/ 
      Handler: app.test_handler # this and the one above are a path to a handler
      Runtime: python3.13