name: handler_tests

on: 
    pull_request:
        types: [opened, ready_for_review, synchronize]
    push:
        branches:
            '**' # all branches

jobs:
    test:
        runs-on: ubuntu-latest

        steps:
        - name: Checkout code
          uses: actions/checkout@v4
        - name: Set up Python
          uses: actions/setup-python@v4
          with:
            python-version: '3.13'
        - name: Install dependencies
          working-directory: .
          run: |
            python -m venv .venv
            source .venv/bin/activate
            which pip
            pip install -r requirements.txt
        - name: Run tests
          working-directory: ./endpoints/
          run: |
            which python
            source .venv/bin/activate
            python -m pytest ../tests
            
            